### ISSUE TITLE
echo with odd number of quotes ' "

### ISSUE THREAD

**Issue by xhelp00** [xhelp00/minishell#16]
echo works with even number of quotes only
![image](https://github.com/xhelp00/minishell/assets/111277585/a4d6d9fb-488e-4fd1-b2a4-e4cac5f55ccc)

**Comment by xhelp00** [comment]
parser.c:53 in fill_list

**Comment by fv99** [comment]
Not interpret unclosed quotes or special characters which are not required by the
subject such as \ (backslash) or ; (semicolon

**Comment by xhelp00** [comment]
fixed with workaround
